<?php

namespace Modules\Ap\Entities\Views;

use App\Models\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Modules\Gp\Enums\LnStatusCodeEnum;

class VwApAccount extends Model
{
    use HasFactory;

    protected $table = 'vw_ap_acnt_list';
    protected $primaryKey = 'acntno';
    public $incrementing = false;
    protected $keyType = 'string';

    protected $fillable = [
        'acntno',
        'brchno',
        'custno',
        'segcode',
        'prodcode',
        'curcode',
        'name',
        'name2',
        'catcode',
        'loantype',
        'purpcode',
        'intrate',
        'termlen',
        'termbasis',
        'begdate',
        'enddate',
        'approvdate',
        'approvamount',
        'openeddate',
        'closeddate',
        'advdate',
        'advamount',
        'theorbal',
        'princbal',
        'capbint',
        'capcint',
        'capfint',
        'paidlon',
        'paidint',
        'baseintdaily',
        'comintdaily',
        'fineintdaily',
        'baseint2cap',
        'comint2cap',
        'fineint2cap',
        'adjbint2cap',
        'adjcint2cap',
        'adjfint2cap',
        'dueprinc',
        'dueint',
        'arreardate',
        'clscode',
        'condchg',
        'fintxncount',
        'lasttxndate',
        'balchanged',
        'advchanged',
        'arrearchanged',
        'bratechanged',
        'cratechanged',
        'fratechanged',
        'prevstatus',
        'closedtype',
        'lonnum',
        'appno',
        'nextpayday',
        'nexttheorbal',
        'capfreq',
        'capday',
        'repayacntno',
        'repaytype',
        'payamount',
        'payfreq',
        'payday',
        'paymonth',
        'recalcschd',
        'nextcapday',
        'finestop',
        'finestopdate',
        'ctacruel',
        'ctacntno',
        'repaypriority',
        'redrawlimit',
        'comdate',
        'tmp_princbal',
        'tmp_capbint',
        'tmp_capcint',
        'tmp_capfint',
        'tmp_acrbint',
        'tmp_acrcint',
        'tmp_acrfint',
        'moramount',
        'arreardateint',
        'ctcomacruel',
        'ctcomacntno',
        'ctfineacruel',
        'ctfineacntno',
        'baseroundint',
        'comroundint',
        'fineroundint',
        'arreardatecom',
        'duecom',
        'finecomintdaily',
        'finecomroundint',
        'tmp_statuscode',
        'tmp_brchno',
        'tmp_prodcode',
        'tmp_clscode',
        'hide',
        'tmp_theorbal',
        'ctlineacntno',
        'reserved',
        'tmp_begdate',
        'tmp_enddate',
        'tmp_dueprinc',
        'tmp_dueint',
        'tmp_duecom',
        'tmp_arreardate',
        'tmp_arreardateint',
        'tmp_arreardatecom',
        'comcustno',
        'statusbad',
        'tellerbad',
        'trackno',
        'intratecom',
        'intratefine',
        'intratecomtier',
        'intratefinetier',
        'invacntno',
        'collacntno',
        'prevprincbal',
        'tmp_bal',
        'prevbal',
        'inffreq',
        'auditmanager',
        'gotinsurance',
        'comamount',
        'dueamount',
        'payday2',
        'statusbadapp',
        'cecustno',
        'lasttellertxndate',
        'txndef',
        'subpurpcode',
        'insureorgcode',
        'tmp_baseintdaily',
        'tmp_comintdaily',
        'tmp_fineintdaily',
        'rootacntno',
        'linebal',
        'linebasebal',
        'linemodule',
        'linecurcode',
        'lgriskrate',
        'lcriskrate',
        'lcunusedriskrate',
        'lgunusedriskrate',
        'tmp_redrawlimit',
        'lglcenddate',
        'tellerfunc',
        'createddate',
        'tmp_finecomintdaily',
        'intstoptype',
        'intstopclass',
        'cetype',
        'cectacntno',
        'ceinvacntno',
        'ceinvintrate',
        'cemovecomint',
        'cemovefintint',
        'autocls',
        'intstopteller',
        'repayrtypecode',
        'defaultamount',
        'defaultdate',
        'capbinte',
        'nrsfromfile',
        'tmp_dueamount',
        'prevdueamount',
        'tmp_capbinte',
        'isdphold',
        'dpacntholdid',
        'escapemonths',
        'assrlnacntno',
        'clscodetrm',
        'clscodeqlt',
        'tmp_clscodetrm',
        'tmp_clscodeqlt',
        'finelastacrueddate',
        'sourcecode',
        'bintrateruleid',
        'greenpurpcode',
        'greensubpurpcode',
        'riskmanager',
        'sellermanager',
        'analysismanager',
        'sendcreditbureo',
        'statusid',
        'instid',
        'created_by',
        'updated_by',
        'created_at',
        'updated_at',
        'custtypecode',
        'custid',
        'numarreardatediff',
        'numarreardateintdiff',
    ];

    protected $appends = ['statusname'];

    public function getStatusnameAttribute()
    {
        return __('messages.' . LnStatusCodeEnum::toString($this->statusid));
    }
    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'acntno' => 'string',
        'updated_at' => 'date:Y-m-d H:i:s',
        'created_at' => 'date:Y-m-d H:i:s',
        'begdate'=>'date:Y-m-d',
        'enddate'=>'date:Y-m-d',
        'approvdate'=>'date:Y-m-d',
        'closeddate'=>'date:Y-m-d',
        'advdate'=>'date:Y-m-d',
        'arreardate'=>'date:Y-m-d',
        'lasttxndate'=>'date:Y-m-d',
        'finestopdate'=>'date:Y-m-d',
        'comdate'=>'date:Y-m-d',
        'arreardateint'=>'date:Y-m-d',
        'arreardatecom'=>'date:Y-m-d',
        'tmp_begdate'=>'date:Y-m-d',
        'tmp_enddate'=>'date:Y-m-d',
        'tmp_arreardate'=>'date:Y-m-d',
        'tmp_arreardateint'=>'date:Y-m-d',
        'tmp_arreardatecom'=>'date:Y-m-d',
        'lasttellertxndate'=>'date:Y-m-d',
        'lglcenddate'=>'date:Y-m-d',
        'createddate'=>'date:Y-m-d',
        'defaultdate'=>'date:Y-m-d',
        'finelastacrueddate'=>'date:Y-m-d',
        'payamount' => 'float',
        'paybaseamount' => 'float',
        'approvamount' => 'float',
        'advamount' => 'float',
        'theorbal' => 'float',
        'princbal' => 'float',
        'capbint' => 'float',
        'capcint' => 'float',
        'capfint' => 'float',
        'paidlon' => 'float',
        'paidint' => 'float',
        'comamount' => 'float',
        'dueamount' => 'float',
        'ctacntno' => 'float',
        'moramount' => 'float',
        'ctcomacntno' => 'float',
        'ctfineacntno' => 'float',
        'comint2cap' => 'float',
        'comintdaily' => 'float',
        'ceinvintrate' => 'float',
        'capbinte' => 'float',
        'baseint2cap' => 'float',
        'baseintdaily' => 'float',
        'adjbint2cap' => 'float',
        'adjcint2cap' => 'float',
        'adjfint2cap' => 'float',
        'defaultamount' => 'float',
        'duecom' => 'float',
        'dueint' => 'float',
        'dueprinc' => 'float',
        'finecomintdaily' => 'float',
        'finecomroundint' => 'float',
        'fineint2cap' => 'float',
        'fineintdaily' => 'float',
        'intrate' => 'float',
        'intratecom' => 'float',
        'intratefine' => 'float',
        'linebal' => 'float',
        'linebasebal' => 'float',
        'nextpaysumint' => 'float',
        'nexttheorbal' => 'float',
        'prevbal' => 'float',
        'prevdueamount' => 'float',
        'prevprincbal' => 'float',
        'redrawlimit' => 'float',
        'repay_bal' => 'float',
        'sumbalance' => 'float',
        'sumbaseint2cap' => 'float',
        'sumcomint2cap' => 'float',
        'sumfineint2cap' => 'float',
        'ctlineacntno' => 'float',
        'cectacntno' => 'float',
        'numarreardatediff' => 'integer',
        'numarreardateintdiff' => 'integer',
    ];

}
