<?php

namespace Modules\Ap\Entities;

use App\Models\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class ApAcntLn extends Model
{
    use HasFactory;

    protected $table = 'ap_acnt_ln';

    protected $fillable = [
        'acnt_code',
        'name',
        'name2',
        'company_code',
        'prod_code',
        'cur_code',
        'brch_code',
        'cust_code',
        'cust_name',
        'acnt_manager',
        'first_acnt_manager',
        'seg_code',
        'status',
        'slevel',
        'class_no',
        'start_date',
        'end_date',
        'term_len',
        'approv_date',
        'approv_amount',
        'purpose',
        'sub_purpose',
        'flag_stopped',
        'flag_stopped_int',
        'flag_wroff_princ',
        'flag_wroff_int',
        'is_not_auto_class',
        'last_bill_no',
        'repay_acnt_code',
        'repay_priority',
        'active_nrs_version',
        'daily_basis_code',
        'flag_move_sa',
        'sa_date',
        'com_revolving',
        'last_txn_date',
        'adv_date',
        'adv_amount',
        'closed_date',
        'created_by',
        'created_at',
        'los_acnt_code',
        'flag_sec',
        'prod_type',
        'payment_method',
        'sec_type',
        'sec_from_acnt',
        'sec_to_acnt',
        'sec_tmp_acnt',
        'sec_inc_exp_acnt',
        'extend_count',
        'sold_date',
        'acquired_date',
        'sold_seq_txn',
        'acquired_seq_txn',
        'last_seq_txn',
        'class_no_trm',
        'class_no_qlt',
        'los_multi_acnt',
        'repay_acnt_code_other_com',
        'is_browse_acnt_other_com',
        'is_linked_secz',
        'repay_acnt_sys_no',
        'last_accrual_date',
        'prod_name',
        'brch_name',
        'class_qlt_name',
        'seg_name',
        'class_name',
        'class_trm_name',
        'status_name',
        'acnt_manager_name',
        'first_acnt_manager_name',
        'cust_type',
        'princ_bal',
        'cont_available',
        'revol_amt',
        'theor_bal',
        'bill_princ_bal',
        'bill_baseint_bal',
        'bill_comint_bal',
        'bill_fineb_bal',
        'bill_finep_bal',
        'acr_baseint_bal',
        'avail_com_bal',
        'used_com_bal',
        'prepaid_baseint_bal',
        'total_bal',
        'total_bill',
        'bill_princ_date',
        'bill_baseint_date',
        'bill_fine_date',
        'term_basis',
        'min_term_unit',
        'max_term_unit',
        'def_term_unit',
        'autooff_int',
        'autooff_option_int',
        'autooff_cls_int',
        'autooff_dueopt_int',
        'autooff_duedays_int',
        'autochg_cls',
        'autochg_option_cls',
        'autochg_due_cls',
        'autochg_formulaid_cls',
        'crt_billbint_topay',
        'allowed_cam',
        'fine_condition',
        'fine_grace',
        'flag_stopped_name',
        'flag_stopped_int_name',
        'flag_move_sa_name',
        'repay_acnt_name',
        'purpose_name',
        'sub_purpose_name',
        'is_secure',
        'next_schd_date',
        'next_schd_amt',
        'next_schd_int',
        'cat_code',
        'cat_sub_code',
        'cat_sub_name',
        'cat_name',
        'sec_acnt_code',
        'sec_acnt_name',
        'statusid',
        'instid',
        'userid',
        'id',
        'sys_no',
        'acnt_type',
        'limit',
        'princ_bal_on',
        'acr_commint_bal',
        'bill_commint_bal_on',
        'fine_min_duebal',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'sys_no' => 'integer',
        'instid' => 'integer',
        'is_secure' => 'integer',
        'theor_bal' => 'double',
        'princ_bal_on' => 'double',
        'acr_commint_bal' => 'double',
        'bill_princ_bal' => 'double',
        'bill_baseint_bal' => 'double',
        'bill_comint_bal' => 'double',
        'bill_fineb_bal' => 'double',
        'bill_finep_bal' => 'double',
        'acr_baseint_bal' => 'double',
        'avail_com_bal' => 'double',
        'used_com_bal' => 'double',
        'prepaid_baseint_bal' => 'double',
        'total_bal' => 'double',
        'princ_bal' => 'double',
        'revol_amt' => 'double',
        'limit' => 'double',
        'next_schd_int' => 'double',
        'next_schd_amt' => 'double',
        'approv_amount' => 'double',
        'crt_billbint_topay' => 'double',
        'adv_amount' => 'double',
        'bill_commint_bal_on' => 'double',
        'cont_available' => 'double',
        'com_revolving' => 'double',
        'total_bill' => 'double',
        'max_term_unit' => 'integer',
        'def_term_unit' => 'integer',
        'cust_type' => 'integer',
        'term_len' => 'integer',
        'fine_grace' => 'integer',
        'fine_min_duebal' => 'integer',
        'los_multi_acnt' => 'integer',
        'autooff_int' => 'integer',
        'sec_type' => 'integer',
        'flag_move_sa' => 'integer',
        'flag_stopped' => 'integer',
        'flag_stopped_int' => 'integer',
        'allowed_cam' => 'integer',
        'repay_priority' => 'integer',
        'class_no_trm' => 'integer',
        'autochg_cls' => 'integer',
        'autooff_duedays_int' => 'integer',
        'flag_stopped_int' => 'integer',
        'first_acnt_manager' => 'integer',
        'repay_acnt_sys_no' => 'integer',
        'is_not_auto_class' => 'integer',
        'last_bill_no' => 'integer',
        'flag_wroff_princ' => 'integer',
        'acnt_manager' => 'integer',
        'is_browse_acnt_other_com' => 'integer',
        'slevel' => 'integer',
        'class_no' => 'integer',
        'payment_method' => 'integer',
        'flag_wroff_int' => 'integer',
        'flag_sec' => 'integer',
        'active_nrs_version' => 'integer',
        'min_term_unit' => 'integer',
        'class_no_qlt' => 'integer',
        'is_linked_secz' => 'integer',
        'created_by' => 'integer',
    ];

}
